#!/bin/bash
# Write a simple Bash program where your first name and last name are assigned to different variables, and the script prints out your full name

firstname="Eniola"
lastname="Onabowale"


# Write a version where the strings are printed on the same line and a version where the strings are printed on different lines

echo "$firstname $lastname"
echo -e "$firstname\n$lastname"

#Bash Story One

#Create a new folder titled your name

$ mkdir EniolaOnabowale

#Create another new directory titled biocomputing and change to that directory with one line of command

$ mkdir biocomputing && cd biocomputing

#Download these 3 files:
https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna 
https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk 

wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk 
wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk

#OH! You made a mistake. You have to move the .fna file to the folder titled your name directly. (Do this with one command.)

$ mv biocomputing/wildtype.fna EniolaOnabowale/

#OH No! The gbk file is a duplicate, they are actually the same thing. Please delete it

$ rm wildtype.gbk

#Can you confirm if the file is mutant or wild type

$ grep tatatata wildtype.fna 

#If it is mutant, print all the lines that show it is a mutant into a new file

$ grep tatatata wildtype.fna > mutant

# Clear your terminal space and print all the commands you have used today.
$ clear 
$ history

#List the files in the two folders and share a screenshot of your terminal below
$ ls && ls ../biocomputing

#Exit terminal
$ exit


#BASH STORY TWO 

#Use the figlet command to draw a graphical representation of your name.
$ sudo apt install figlet
$ figlet Eniola

#In your home directory, create a folder called compare.
$ mkdir compare

# Download this file [5MB] into your the compare directory: https://www.bioinformatics.babraham.ac.uk/training/Introduction%20to%20Unix/unix_intro_data.tar.gz 
$ wget https://www.bioinformatics.babraham.ac.uk/training/Introduction%20to%20Unix/unix_intro_data.tar.gz 

#Unzip using gunzip command
$ gunzip unix_intro_data.tar.gz

#Then, untar the .tar file with tar command
$ tar -xvf unix_intro_data.tar

#Get into seqmonk_genomes/Saccharomyces cerevisiae/EF4 and identify the rRNAs present in Mito.dat.
$ cd seqmonk_genomes/”Saccharomyces cerevisiae”/EF4
$ grep “rRNA” Mito.dat 

#Using cp copy Mito.dat into the compare directory
$ cp Mito.dat ../ ../ ..

#Change Mito to Mitochondrion in the ID and AC header lines
$ nano Mito.dat

#Rename the file from Mito.dat to Mitochondrion.txt
$ mv Mito.dat Mitochondrion.txt

#Calculate the total number of lines in lane8_DD_P4_TTAGGC_L008_R1.fastq.gz
$ wc -l lane8_DD_P4_TTAGGC_L008_R1.fastq.gz 

#Calculate the total number of lines in lane8_DD_P4_TTAGGC_L008_R1.fastq.gz
$ wc -l *.fastq.gz > total_fast.gz_line_number






