#!/bin/bash

#Download the DNA.fa file
wget https://raw.githubusercontent.com/HackBio-Internship/wale-home-tasks/main/DNA.fa

#Count the number of sequences in DNA.fa
grep -c ">" DNA.fa

#Write a one-line command in Bash to get the total A, T, G & C counts
grep -Eo 'A|T|G|C' DNA.fa | sort | uniq -c | awk '{print $2": "$1}'

#Set up a conda (anaconda, miniconda or mini forge) environment on your terminal.

shasum -a 256 Miniconda3-py37_4.12.0-Linux-x86_64.sh
chmod +x Miniconda3-py37_4.12.0-Linux-x86_64.sh
./Miniconda3-py37_4.12.0-Linux-x86_64.sh
source ~/.bashrc

#Install your three software

sudo apt install fastp
sudo apt install fastqc
sudo apt install multiqc

#Download the sample datasets from https://github.com/josoga2/yt-dataset/tree/main/dataset

wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/ACBarrie_R1.fastq.gz?raw=true/ -O ACBarrie_R1.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/ACBarrie_R2.fastq.gz?raw=true/ -O ACBarrie_R2.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Alsen_R1.fastq.gz?raw=true/ -O Alsen_R1.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Alsen_R2.fastq.gz?raw=true/ -O Alsen_R2.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Baxter_R1.fastq.gz?raw=true/ -O Baxter_R1.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Baxter_R2.fastq.gz?raw=true/ -O Baxter_R2.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Chara_R1.fastq.gz?raw=true/ -O Chara_R1.fastq.gz
wget https://github.com/josoga2/yt-dataset/blob/main/dataset/raw_reads/Chara_R2.fastq.gz?raw=true/ -O Chara_R2.fastq.gz

#Create a folder called output

mkdir output

#Implement the three software on the downloaded files (sample datasets) and send all outputs to the output folder

#Implementing fastp (to trim adapters and poor quality reads)

touch trim.sh
nano trim.sh

SAMPLES=(
  "ACBarrie"
  "Alsen"
  "Baxter"
  "Chara"
  "Drysdale"
)

for SAMPLE in "${SAMPLES[@]}"; do

  fastp \
    -i "$PWD/${SAMPLE)_R1.fastq.gz" \
    -I "$PWD/${SAMPLE)_R2.fastq.gz" \
    -o "output/${SAMPLE}_R1.fastq.gz" \
    -O "output/${SAMPLE}_R2.fastq.gz" \
    --html "output/${SAMPLE}_fastp.html" 
done

bash trim.sh
mv qc_reads trimmed_reads
mv ACBarrie_fastp.html Baxter_fastp.html Alsen_fastp.html Chara_fastp.html /home/eniolaonabowale/output/


#Implementing fastqc (for Quality Control)

fastqc ACBarrie_R1.fastq.gz -o output
fastqc ACBarrie_R2.fastq.gz -o output
fastqc Alsen_R1.fastq.gz -o output
fastqc Alsen_R2.fastq.gz -o output
fastqc Chara_R1.fastq.gz -o output
fastqc Chara_R2.fastq.gz -o output

#Implementing MultiQC (for Quality Control and to aggregate all the html reports into a single file )

 multiqc output
 mv multiqc_report.html output
 





